
package com.chathurangaonline.apache.cxf.jaxws.spring.samples.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.chathurangaonline.apache.cxf.jaxws.spring.samples.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://samples.spring.jaxws.cxf.apache.chathurangaonline.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://samples.spring.jaxws.cxf.apache.chathurangaonline.com/", className = "com.chathurangaonline.apache.cxf.jaxws.spring.samples.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://samples.spring.jaxws.cxf.apache.chathurangaonline.com/", className = "com.chathurangaonline.apache.cxf.jaxws.spring.samples.MultiplyResponse")
    public double multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
